Make the "port forwarding create" command idempotent
The `port forwarding create` command would exit with an error
if you attempted to create a forwarding configuration that already exists.
This made it difficult to identify actual failures.

This commit updates the `port forwarding create` command so that it is not
an error if the requested forwarding already exists.

The old behavior was:

    $ openstack esi port forwarding create 192.168.11.31 128.31.20.118 -p 8888
    +--------------------------------------+---------------+---------------+----------+---------------+---------------+
    | ID                                   | Internal Port | External Port | Protocol | Internal IP   | External IP   |
    +--------------------------------------+---------------+---------------+----------+---------------+---------------+
    | 43c96be3-861d-4818-a32a-079a93b6f9c4 |          8888 |          8888 | tcp      | 192.168.11.31 | 128.31.20.118 |
    +--------------------------------------+---------------+---------------+----------+---------------+---------------+
    $ openstack esi port forwarding create esi-MOC-R4PAC24U35-S1B-provisioning 128.31.20.118 -p 8888 -p 8889
    BadRequestException: 400: Client Error for url:
    https://esi.massopen.cloud:13696/v2.0/floatingips/be4b2718-ec5f-4722-80b5-485c421e4a72/port_forwardings,
    Bad port_forwarding request: A duplicate port forwarding entry with
    same attributes already exists, conflicting values are
    {'floatingip_id': 'be4b2718-ec5f-4722-80b5-485c421e4a72',
    'external_port': 8888, 'protocol': 'tcp'}.

The new behavior looks like this:

    $ openstack esi port forwarding create 192.168.11.31 128.31.20.118 -p 8888
    +--------------------------------------+---------------+---------------+----------+---------------+---------------+
    | ID                                   | Internal Port | External Port | Protocol | Internal IP   | External IP   |
    +--------------------------------------+---------------+---------------+----------+---------------+---------------+
    | 43c96be3-861d-4818-a32a-079a93b6f9c4 |          8888 |          8888 | tcp      | 192.168.11.31 | 128.31.20.118 |
    +--------------------------------------+---------------+---------------+----------+---------------+---------------+
    $ openstack esi port forwarding create esi-MOC-R4PAC24U35-S1B-provisioning 128.31.20.118 -p 8888 -p 8889
    +--------------------------------------+---------------+---------------+----------+---------------+---------------+
    | ID                                   | Internal Port | External Port | Protocol | Internal IP   | External IP   |
    +--------------------------------------+---------------+---------------+----------+---------------+---------------+
    | exists                               |          8888 |          8888 | tcp      | 192.168.11.31 | 128.31.20.118 |
    | d7d56201-232a-41fe-8ae6-1f6fb88a37d3 |          8889 |          8889 | tcp      | 192.168.11.31 | 128.31.20.118 |
    +--------------------------------------+---------------+---------------+----------+---------------+---------------+